version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: jhire_user
      POSTGRES_PASSWORD: jhire_password
      POSTGRES_DB: jhire_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://jhire_user:jhire_password@db:5432/jhire_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

volumes:
  postgres_data:
